name: Go Build

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.6'  # Updated to match project requirements

    - name: Install dependencies
      run: go mod tidy

    - name: Build main application
      run: go build -v ./cmd/oauth-bridge

    - name: Build client examples
      run: |
        cd examples/client-usage
        go mod tidy
        go build -v

    - name: Run tests
      run: go test -v ./...
