name: Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag to release (e.g., v1.0.0)"
        required: true
        type: string

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23.6"

      - name: Get version
        id: version
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "version=${{ inputs.tag }}" >> $GITHUB_OUTPUT
          else
            echo "version=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          fi

      - name: Install dependencies
        run: go mod tidy

      - name: Run tests
        run: go test ./...

      - name: Create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.version.outputs.version }}
          release_name: OAuth Bridge ${{ steps.version.outputs.version }}
          body: |
            ## OAuth Bridge ${{ steps.version.outputs.version }}

            A secure OAuth bridge service for GitHub App installations in on-premises SSD environments.

            ### What's New
            - Clean single-module architecture
            - Simplified client SDK import: `github.com/OpsMx/oauth-bridge`
            - Enhanced ECC JWT authentication
            - Zero-ingress security architecture

            ### Installation

            **Client SDK:**
            ```bash
            go get github.com/OpsMx/oauth-bridge@${{ steps.version.outputs.version }}
            ```

            **Server Binaries:**
            Download the appropriate binary for your platform from the assets below.

            ### Usage

            **Client SDK:**
            ```go
            import "github.com/OpsMx/oauth-bridge"

            client, err := oauthbridge.NewClient("my-service")
            ```

            **Server:**
            ```bash
            ./oauth-bridge -configFile /app/config/oauth-bridge.yaml
            ```

            See the [README](https://github.com/OpsMx/oauth-bridge/blob/main/README.md) for complete documentation.
          draft: false
          prerelease: false

      # Add more upload steps for other platforms as needed

